"""Añadir columna image_path a ImageUpload

Revision ID: 287e8655f074
Revises: e40051afad10
Create Date: 2025-05-01 21:06:54.468670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '287e8655f074'
down_revision = 'e40051afad10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_upload', schema=None) as batch_op:
        batch_op.drop_column('image_path')

    # ### end Alembic commands ###
